[workspace]
authors = ["Brian E. Granger <ellisonbg@gmail.com>"]
channels = ["conda-forge"]
name = "image"
platforms = ["osx-arm64", "linux-aarch64", "linux-64"]
version = "0.1.0"

[tasks]
start = "python main.py"

[dependencies]
jupyter = "*"
nbformat = "*"
nbconvert = "*"
ipykernel = "*"
awscli = "*"
